language: python
python:
  - 3.8
before_install:
  - python -m pip install --upgrade pip
  - pip install nose
  - pip install coverage
install:
  - python setup.py build
  - python setup.py egg_info
  - pip install -e .
script:
  - coverage run -m nose lightdock/
after_success:
  - bash <(curl -s https://codecov.io/bash)
